### ISSUE TITLE
Build & Automate docker image build

### ISSUE THREAD

**Issue by Clivern** [silverbackhq/silverback#155]

**Comment by Clivern** [comment]
It would be nice if you update the dockerfile to a multistage build. 
On first stage
- install requirements.
- run the following to build assets and move them to static dir.
```
$ python manage.py collectstatic
```

On the second stage:
- we need to copy the final code from builder stage.
 
I can take care of the automate part using travis

**Comment by sourabhdeshmukh** [comment]
Ok Thanks I will try my hand on this. Thank You :) for details.

**Comment by sourabhdeshmukh** [comment]
I have updated the Dockerfile depending upon changes as you mentioned. I will send PR tomorrow.
It will count in my Hactoberfest 2019. :)

**Comment by Clivern** [comment]
Nice, Thanks @sourabhdeshmukh. I also automated the image build, you can see that on master branch https://hub.docker.com/r/clivern/silverback

**Comment by sourabhdeshmukh** [comment]
There is something wrong with https://hub.docker.com/r/clivern/silverback image. 
When I executed following steps
Steps executed: 
       docker pull clivern/silverback
       docker run -d -p 8000:8000 clivern/silverback:latest

Container spawn up successfully but when redirected to browser 

Error Message:  On browser http://0.0.0.0:8000 error
    OperationalError at /
    no such table: django_session

[error.log](https://github.com/silverbackhq/silverback/files/3671150/error.log)

**Comment by Clivern** [comment]
Yeah because it still not ready yet, after i merge your PR, will provide default configs to make stuff work

**Comment by sourabhdeshmukh** [comment]
Sent PR for review #163

**Comment by Clivern** [comment]
Thanks @sourabhdeshmukh

**Comment by sourabhdeshmukh** [comment]
Thanks @Clivern for allowing me to contribute. :) I will check with other issues if I can help.
