### ISSUE TITLE
Add French Translation.

### ISSUE THREAD

**Issue by Clivern** [silverbackhq/silverback#156]

**Comment by arxcdr** [comment]
Hey there, I can do this one if you want. Is there any special process to follow for contributions or do I just fork, translate and create a PR?

**Comment by Clivern** [comment]
Thanks @arxcdr for looking into this, As you said fork, translate, create a PR & I will add Hacktoberfest label to your PR then merge.

**Comment by arxcdr** [comment]
Thanks for confirming @Clivern - I'll get started this afternoon and hopefully should be able to finish the file by the beginning of next week for Hacktoberfest!

**Comment by arxcdr** [comment]
Actually now that I've looked at the file more closely, I think it might take a bit longer than that but I'll do my best. Are there any restrictions I should be aware of for the translation otherwise (character limit per segment, special characters not to use, etc.)?

**Comment by Clivern** [comment]
There is no limitations, and we can merge whatever you finish.

**Comment by arxcdr** [comment]
Perfect, thanks!

**Comment by arxcdr** [comment]
OK it's going at a good pace, I've translated and spellchecked the first 600 lines already (about 25% of the total). Is it okay with you if I wait till Tuesday to create my PRs so they all count for Hacktoberfest? I'd like to create 4 PRs for roughly 600 lines each.

**Comment by Clivern** [comment]
of course you can split over 4 PRs & open PRs anytime within october. Anyway i assigned the task to you. Thanks!

**Comment by Clivern** [comment]
Thanks @arxcdr
