### ISSUE TITLE
Activate stdout logging for k8s deployment!

### ISSUE THREAD

**Issue by Clivern** [silverbackhq/silverback#159]

**Comment by sgaist** [comment]
Hi,

Can you give a bit more details about this ?
Maybe some starting point to look into ?

**Comment by Clivern** [comment]
Hi @sgaist

Thanks for looking into this but it is actually a testing task more than coding task and fix whatever not working.

So once this issue https://github.com/silverbackhq/silverback/issues/155 fixed, I will update dockerfile Env vars to activate stdout logging and test that image. Stdout logging is already supported based on this line
https://github.com/silverbackhq/silverback/blob/master/app/settings/basic.py#L225

**Comment by Clivern** [comment]
```
$ docker run --name my-silverback -d -p 8000:8000 clivern/silverback:latest
```
